[hardened]
web1 ansible_host=20.112.0.202
web2 ansible_host=4.155.56.169

[hardened:vars]
ansible_user=azureadmin
ansible_ssh_private_key_file=~/.ssh/ansible_lab
ansible_python_interpreter=/usr/bin/python3
